name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    # only build/deploy main branch on pushes
    if:
      ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') &&
      github.event_name == 'push' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Caprover
        uses: ariaieboy/caprover-deploy@1.2.2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          server: ${{ secrets.CAPROVER_HOST }}
          password: ${{secrets.CAPROVER_PASSWORD}}
          app: "food-truck-tracker"
