name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
env:
  CONTEXT_DIR: './'
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE: Dockerfile
  CAPROVER_APP: food-truck-tracker
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
            echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
            export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
            echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
            registry: ${{ env.DOCKER_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Release to DockerHub
        shell: bash
        run: ./build_and_push.sh
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
            server: ${{ secrets.CAPROVER_HOST }}
            app: ${{ env.CAPROVER_APP }}
            token: '${{ secrets.CAPROVER_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}'
