name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build and Deploy
        uses: adamghill/build-docker-and-deploy-to-caprover@v1
        with:
          caprover-app-name: food-truck-tracker
          github-token: ${{ secrets.GITHUB_TOKEN }}
          caprover-server-url: ${{ secrets.CAPROVER_HOST }}
          caprover-app-token: ${{ secrets.CAPROVER_APP_TOKEN }}
