name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
env:
  CONTEXT_DIR: './'
  IMAGE_NAME: ${{ github.repository }}
  DOCKERFILE: Dockerfile
  CAPROVER_APP: food-truck-tracker
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.7.0
        
      - name: Login to Container Registry
        uses: docker/login-action@v2.2.0
        with:
              registry: ${{ env.DOCKER_REGISTRY }}
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest)" >> $GITHUB_ENV
  
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.IMAGE_URL }}
  
      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_HOST }}"
          app: "${{ env.CAPROVER_APP }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
